#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/aeguchi/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/aeguchi/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/aeguchi/Documents/workspace/SeriousDevelopment/Program_repo/x86_64/.libs/libnrnmech.so" "$@"
